/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karandeep.el_seguro;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 91701
 */
public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Admin Screen");
        setSize(900,600);
        jDesktopPane1.setBounds(this.getBounds());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addEmployee = new javax.swing.JMenuItem();
        updateEmployee = new javax.swing.JMenuItem();
        deleteEmployee = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addPlan = new javax.swing.JMenuItem();
        removePlan = new javax.swing.JMenuItem();
        updatePlan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addBranch = new javax.swing.JMenuItem();
        updateBranch = new javax.swing.JMenuItem();
        deleteBranch = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jMenu1.setText("Employee Operations");

        addEmployee.setText("Add Employee");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(addEmployee);

        updateEmployee.setText("Update Employee");
        updateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(updateEmployee);

        deleteEmployee.setText("Delete Employee");
        deleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(deleteEmployee);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Plan Operations");

        addPlan.setText("Add Plan");
        addPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlanActionPerformed(evt);
            }
        });
        jMenu2.add(addPlan);

        removePlan.setText("Remove Plan");
        removePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePlanActionPerformed(evt);
            }
        });
        jMenu2.add(removePlan);

        updatePlan.setText("Update Plan");
        updatePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlanActionPerformed(evt);
            }
        });
        jMenu2.add(updatePlan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Branch Operations");

        addBranch.setText("Add Branch");
        addBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBranchMouseClicked(evt);
            }
        });
        addBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchActionPerformed(evt);
            }
        });
        jMenu3.add(addBranch);

        updateBranch.setText("Update Branch");
        updateBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBranchActionPerformed(evt);
            }
        });
        jMenu3.add(updateBranch);

        deleteBranch.setText("Delete Branch");
        deleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBranchActionPerformed(evt);
            }
        });
        jMenu3.add(deleteBranch);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
        AddEmployee addEmployee = new AddEmployee("Add");
     addEmployee.setVisible(true);
     jDesktopPane1.add(addEmployee);
        try {
            addEmployee.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void updateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeActionPerformed
        // TODO add your handling code here:
        DeleteEmployee addEmployee = new DeleteEmployee("Update",jDesktopPane1);
     addEmployee.setVisible(true);
     jDesktopPane1.add(addEmployee);
        try {
            addEmployee.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_updateEmployeeActionPerformed

    private void addPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlanActionPerformed
        // TODO add your handling code here:
        AddPlan addPlan = new AddPlan("Add");
     addPlan.setVisible(true);
     jDesktopPane1.add(addPlan);
        try {
            addPlan.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addPlanActionPerformed

    private void removePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePlanActionPerformed
        // TODO add your handling code here:
        DeletePlan deletePlan = new DeletePlan("Delete",jDesktopPane1);
     deletePlan.setVisible(true);
     jDesktopPane1.add(deletePlan);
        try {
            deletePlan.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_removePlanActionPerformed

    private void addBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchActionPerformed
     AddBranch addBranch = new AddBranch("Add");
     addBranch.setVisible(true);
     jDesktopPane1.add(addBranch);
        try {
            addBranch.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBranchActionPerformed

    private void updateBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBranchActionPerformed
        // TODO add your handling code here:
        DeleteBranch addBranch = new DeleteBranch("Update",jDesktopPane1);
     addBranch.setVisible(true);
     jDesktopPane1.add(addBranch);
        try {
            addBranch.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBranchActionPerformed

    private void deleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBranchActionPerformed
        // TODO add your handling code here:
        DeleteBranch deleteBranch = new DeleteBranch("Delete",jDesktopPane1);
     deleteBranch.setVisible(true);
     jDesktopPane1.add(deleteBranch);
        try {
            deleteBranch.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBranchActionPerformed

    private void updatePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlanActionPerformed
        // TODO add your handling code here:
        DeletePlan deleteplan = new DeletePlan("Update",jDesktopPane1);
     deleteplan.setVisible(true);
     jDesktopPane1.add(deleteplan);
        try {
            deleteplan.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_updatePlanActionPerformed

    private void deleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeActionPerformed
        // TODO add your handling code here:
        DeleteEmployee deleteEmployee = new DeleteEmployee("Delete",jDesktopPane1);
     deleteEmployee.setVisible(true);
     jDesktopPane1.add(deleteEmployee);
        try {
            deleteEmployee.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_deleteEmployeeActionPerformed

    private void addBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBranchMouseClicked
        // TODO add your handling code here:
        AddBranch addBranch = new AddBranch("Add");
     addBranch.setVisible(true);
     jDesktopPane1.add(addBranch);
        try {
            addBranch.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBranchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBranch;
    private javax.swing.JMenuItem addEmployee;
    private javax.swing.JMenuItem addPlan;
    private javax.swing.JMenuItem deleteBranch;
    private javax.swing.JMenuItem deleteEmployee;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem removePlan;
    private javax.swing.JMenuItem updateBranch;
    private javax.swing.JMenuItem updateEmployee;
    private javax.swing.JMenuItem updatePlan;
    // End of variables declaration//GEN-END:variables
}
