/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karandeep.el_seguro;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 91701
 */
public class CashierScreen extends javax.swing.JFrame {

    /**
     * Creates new form CashierScreen
     */
    public CashierScreen() {
        initComponents();
        setTitle("Cashier Screen");
        setSize(900,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        depositPolicyMenu = new javax.swing.JMenu();
        surrenderPolicyMenu = new javax.swing.JMenu();
        revivePolicyMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        depositPolicyMenu.setText("Deposit Policy");
        depositPolicyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositPolicyMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(depositPolicyMenu);

        surrenderPolicyMenu.setText("Surrender Policy");
        surrenderPolicyMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surrenderPolicyMenuMouseClicked(evt);
            }
        });
        surrenderPolicyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surrenderPolicyMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(surrenderPolicyMenu);

        revivePolicyMenu.setText("Revive Policy");
        revivePolicyMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revivePolicyMenuMouseClicked(evt);
            }
        });
        revivePolicyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revivePolicyMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(revivePolicyMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositPolicyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositPolicyMenuActionPerformed
        
        
    }//GEN-LAST:event_depositPolicyMenuActionPerformed

    private void surrenderPolicyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surrenderPolicyMenuActionPerformed
        
    }//GEN-LAST:event_surrenderPolicyMenuActionPerformed

    private void revivePolicyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revivePolicyMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_revivePolicyMenuActionPerformed

    private void surrenderPolicyMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surrenderPolicyMenuMouseClicked
        // TODO add your handling code here:
        PolicyInputScreen status = new PolicyInputScreen("CashierSurrender",jDesktopPane1);
        status.setVisible(true);
        jDesktopPane1.add(status);
        try {
            status.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AgentScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_surrenderPolicyMenuMouseClicked

    private void revivePolicyMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revivePolicyMenuMouseClicked
        // TODO add your handling code here:
        PolicyInputScreen status = new PolicyInputScreen("CashierRevival",jDesktopPane1);
        status.setVisible(true);
        jDesktopPane1.add(status);
        try {
            status.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AgentScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_revivePolicyMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu depositPolicyMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu revivePolicyMenu;
    private javax.swing.JMenu surrenderPolicyMenu;
    // End of variables declaration//GEN-END:variables
}
