/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karandeep.el_seguro;

/**
 *
 * @author 91701
 */
public class ExecutiveScreen extends javax.swing.JFrame {

    /**
     * Creates new form ExecutiveScreen
     */
    public ExecutiveScreen() {
        initComponents();
        setTitle("Executive Screen");
        setSize(900,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        startUnsuranceMenu = new javax.swing.JMenu();
        revivePolicyMenu = new javax.swing.JMenu();
        surrenderPolicyMenu = new javax.swing.JMenu();
        matureCashoutMenu = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        startUnsuranceMenu.setText("Start Insurance");
        startUnsuranceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startUnsuranceMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(startUnsuranceMenu);

        revivePolicyMenu.setText("Revive Policy");
        revivePolicyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revivePolicyMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(revivePolicyMenu);

        surrenderPolicyMenu.setText("Surrender Policy");
        surrenderPolicyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surrenderPolicyMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(surrenderPolicyMenu);

        matureCashoutMenu.setText("Mature Cashout");
        matureCashoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matureCashoutMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(matureCashoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startUnsuranceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startUnsuranceMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startUnsuranceMenuActionPerformed

    private void revivePolicyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revivePolicyMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revivePolicyMenuActionPerformed

    private void surrenderPolicyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surrenderPolicyMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surrenderPolicyMenuActionPerformed

    private void matureCashoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matureCashoutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matureCashoutMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecutiveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecutiveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecutiveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecutiveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecutiveScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu matureCashoutMenu;
    private javax.swing.JMenu revivePolicyMenu;
    private javax.swing.JMenu startUnsuranceMenu;
    private javax.swing.JMenu surrenderPolicyMenu;
    // End of variables declaration//GEN-END:variables
}
