/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karandeep.el_seguro;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 91701
 */
public class ManagerScreen extends javax.swing.JFrame {

    /**
     * Creates new form ManagerScreen
     */
    String username;
    public ManagerScreen(String EmployeeId) {
        initComponents();
        setTitle("Manager Screen");
        setSize(900,600);
        setLocationRelativeTo(null);
        this.username=EmployeeId;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        checkEmployeeDetails = new javax.swing.JMenuItem();
        checkEmployeeComission = new javax.swing.JMenuItem();
        myProfileMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        premiumCollection = new javax.swing.JMenuItem();
        dailyInsuranceReport = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        jMenu1.setText("Employee Operations");

        checkEmployeeDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Office-Customer-Male-Light-icon.png"))); // NOI18N
        checkEmployeeDetails.setText("Check Employee Details");
        checkEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmployeeDetailsActionPerformed(evt);
            }
        });
        jMenu1.add(checkEmployeeDetails);

        checkEmployeeComission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money-icon.png"))); // NOI18N
        checkEmployeeComission.setText("Check Employee Comission");
        checkEmployeeComission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmployeeComissionActionPerformed(evt);
            }
        });
        jMenu1.add(checkEmployeeComission);

        jMenuBar1.add(jMenu1);

        myProfileMenu.setText("My Profile");
        myProfileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myProfileMenuMouseClicked(evt);
            }
        });
        myProfileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(myProfileMenu);

        jMenu3.setText("Daily Report");

        premiumCollection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money-icon.png"))); // NOI18N
        premiumCollection.setText("Premium Collection");
        jMenu3.add(premiumCollection);

        dailyInsuranceReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report-edit-icon.png"))); // NOI18N
        dailyInsuranceReport.setText("Daily Insurance Report");
        dailyInsuranceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyInsuranceReportActionPerformed(evt);
            }
        });
        jMenu3.add(dailyInsuranceReport);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myProfileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myProfileMenuActionPerformed

    private void checkEmployeeComissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmployeeComissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEmployeeComissionActionPerformed

    private void checkEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmployeeDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEmployeeDetailsActionPerformed

    private void dailyInsuranceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyInsuranceReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyInsuranceReportActionPerformed

    private void myProfileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileMenuMouseClicked
        // TODO add your handling code here:
                ViewEmployeeDetailScreen viewDetail = new ViewEmployeeDetailScreen(username);
        viewDetail.setVisible(true);
        jDesktopPane1.add(viewDetail);
        try {
            viewDetail.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AgentScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_myProfileMenuMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem checkEmployeeComission;
    private javax.swing.JMenuItem checkEmployeeDetails;
    private javax.swing.JMenuItem dailyInsuranceReport;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu myProfileMenu;
    private javax.swing.JMenuItem premiumCollection;
    // End of variables declaration//GEN-END:variables
}
